### PR TITLE
Improve the docs folder and included server setup

### PR DESCRIPTION
**Pull request by tkschmidt**

### CODE REVIEW

**Comment by LLautenbacher** [comment]
I updated the main README to reference the new server setup README. 
Otherwise, it looks to be complete from my perspective.

**Comment by tkschmidt** [comment]
@LLautenbacher I'm fine with all changes from your side. Merge at your discretion

**Review by LLautenbacher — APPROVED** [review]

**Comment by tobiasko** [comment]
Should I ask our sys admin for input now?

**Comment by LLautenbacher** [comment]
That would be great! Have him take a look if it covers everything!

**Pull request merged**
